### ISSUE TITLE
Read please!

### ISSUE THREAD

**Issue by nexcrisx** [Schnocker/EAC_dbp#1]
Hello there!

You seem to be very experienced at coding cheats and overall in C+ from your posts on UC.

I'm looking for a coder, who is interested to code for me ESP (Wallhack) in APB:Reloaded (EAC - easy anti cheat).

The only features i'm looking for is enemy box.

I offer 200 USD monthly for this project.

Please add me on discord: excommunicado#1173 if you are interested!

If the price is too low for you, add me anyway i'm sure we can work this out.

I'm hoping to hear back from you soon.

**Comment by Schnocker** [comment]
No, just no..
